# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicehours',
            name='day',
            field=models.CharField(choices=[(1, 'ALL'), (2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday'), (6, 'Friday'), (7, 'Saturday'), (8, 'Sunday')], default=None, max_length=255),
        ),
    ]
