# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations_model', '0003_auto_20160614_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_type', models.CharField(choices=[('food bank', 'Food Bank'), ('meal program', 'Meal Program')], max_length=255)),
                ('meal', models.CharField(choices=[('N/A', 'N/A'), ('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack')], default='N/A', max_length=255)),
                ('requirements', models.CharField(choices=[('all', 'OPEN TO ALL'), ('women 18+', 'WOMEN 18 AND OLDER'), ('American Indians', 'AMERICAN INDIANS ONLY'), ('55+', 'OPEN TO 55+'), ('men 55+', 'OPEN TO MEN 55+'), ('women and children', 'WOMEN AND CHILDREN ONLY'), ('22 and younger', 'YOUTH 22 AND YOUNGER'), ('60+', 'OPEN TO AGES 60+')], default='OPEN TO ALL', max_length=255)),
                ('day', models.CharField(choices=[('EVERYDAY', 'EVERYDAY'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default=None, max_length=255)),
                ('from_hour', models.TimeField(default=None)),
                ('to_hour', models.TimeField(default=None)),
            ],
        ),
        migrations.RemoveField(
            model_name='servicehours',
            name='location',
        ),
        migrations.RemoveField(
            model_name='servicelocation',
            name='meal',
        ),
        migrations.RemoveField(
            model_name='servicelocation',
            name='program_type',
        ),
        migrations.RemoveField(
            model_name='servicelocation',
            name='requirements',
        ),
        migrations.AddField(
            model_name='servicelocation',
            name='latitude',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='servicelocation',
            name='longitude',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='ServiceHours',
        ),
        migrations.AddField(
            model_name='serviceinfo',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_info', to='locations_model.ServiceLocation'),
        ),
    ]
