# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations_model', '0004_auto_20160621_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceinfo',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='locations_model.ServiceLocation'),
        ),
    ]
