# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 22:36
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('locations_model', '0005_auto_20160621_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceinfo',
            name='other_requirements',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('N/A', 'N/A'), ('ID', 'Photo ID'), ('address', 'Proof of Address')], default='N/A', max_length=255),
        ),
    ]
