# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 22:45
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('locations_model', '0006_serviceinfo_other_requirements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceinfo',
            name='other_requirements',
        ),
        migrations.AddField(
            model_name='serviceinfo',
            name='population',
            field=models.CharField(choices=[('all', 'OPEN TO ALL'), ('women 18+', 'WOMEN 18 AND OLDER'), ('American Indians', 'AMERICAN INDIANS ONLY'), ('55+', 'OPEN TO 55+'), ('men 55+', 'OPEN TO MEN 55+'), ('women and children', 'WOMEN AND CHILDREN ONLY'), ('22 and younger', 'YOUTH 22 AND YOUNGER'), ('60+', 'OPEN TO AGES 60+')], default='OPEN TO ALL', max_length=255),
        ),
        migrations.AlterField(
            model_name='serviceinfo',
            name='requirements',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('N/A', 'N/A'), ('Photo ID', 'Photo ID'), ('Proof of Address', 'Proof of Address')], default='N/A', max_length=255),
        ),
    ]
